apiVersion: apps/v1
kind: Deployment
metadata:
  name: nginx
  # label of deployment resources
  labels:
    app: nginx
    tier: frontend
    pupose: Deployment
spec:
  replicas: {{ .Values.deployment.replicas }} # assume this will change if we dont give replicas
  selector:
    matchLabels:
      app: nginx
      tier: frontend
      pupose: Deployment  
  template:
    metadata:
      labels:
        app: nginx
        tier: frontend
        pupose: Deployment
    spec:
      containers:
      - name: nginx
        image: "nginx:{{ .Values.deployment.image }}" # image version frequently changes
        ports:
        - containerPort: 80
---