apiVersion: v1
kind: Service
metadata:
  name: nginx
spec:
  type: NodePort # This is the key difference, it exposes the service on a port on each node
  selector:
    app: nginx
    tier: frontend
    pupose: Deployment  
  ports:
  - protocol: TCP
    port: 80 # The port that the service will expose
    targetPort: 80
    nodePort: {{ .Values.service.nodePort }} # The port on the container that the service will forward to
---